# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='batchtank.proto',
  package='batchtank_messages',
  serialized_pb='\n\x0f\x62\x61tchtank.proto\x12\x12\x62\x61tchtank_messages\"\xcf\x01\n\x0b\x42\x61seMessage\x12*\n\x06sample\x18\x01 \x03(\x0b\x32\x1a.batchtank_messages.Sample\x12\x31\n\x06signal\x18\x02 \x03(\x0b\x32!.batchtank_messages.ControlSignal\x12.\n\x08register\x18\x03 \x01(\x0b\x32\x1c.batchtank_messages.Register\x12\x31\n\tgetSensor\x18\x04 \x01(\x0e\x32\x1e.batchtank_messages.SensorType\"L\n\x08Register\x12,\n\x04type\x18\x01 \x03(\x0e\x32\x1e.batchtank_messages.SensorType\x12\x12\n\nperiodTime\x18\x02 \x01(\x01\"L\n\rControlSignal\x12\r\n\x05value\x18\x01 \x02(\x01\x12,\n\x04type\x18\x02 \x02(\x0e\x32\x1e.batchtank_messages.OutputType\"E\n\x06Sample\x12\r\n\x05value\x18\x01 \x02(\x01\x12,\n\x04type\x18\x02 \x02(\x0e\x32\x1e.batchtank_messages.SensorType*S\n\nSensorType\x12\x10\n\x0cHEATERSENSOR\x10\x00\x12\x10\n\x0c\x43OOLERSENSOR\x10\x01\x12\x0f\n\x0bINLETSENSOR\x10\x02\x12\x10\n\x0cOUTLETSENSOR\x10\x03*C\n\nOutputType\x12\n\n\x06HEATER\x10\x00\x12\n\n\x06\x43OOLER\x10\x01\x12\r\n\tINLETPUMP\x10\x02\x12\x0e\n\nOUTLETPUMP\x10\x03')

_SENSORTYPE = descriptor.EnumDescriptor(
  name='SensorType',
  full_name='batchtank_messages.SensorType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='HEATERSENSOR', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='COOLERSENSOR', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INLETSENSOR', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OUTLETSENSOR', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=476,
  serialized_end=559,
)


_OUTPUTTYPE = descriptor.EnumDescriptor(
  name='OutputType',
  full_name='batchtank_messages.OutputType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='HEATER', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='COOLER', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INLETPUMP', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OUTLETPUMP', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=561,
  serialized_end=628,
)


HEATERSENSOR = 0
COOLERSENSOR = 1
INLETSENSOR = 2
OUTLETSENSOR = 3
HEATER = 0
COOLER = 1
INLETPUMP = 2
OUTLETPUMP = 3



_BASEMESSAGE = descriptor.Descriptor(
  name='BaseMessage',
  full_name='batchtank_messages.BaseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='sample', full_name='batchtank_messages.BaseMessage.sample', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='signal', full_name='batchtank_messages.BaseMessage.signal', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='register', full_name='batchtank_messages.BaseMessage.register', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='getSensor', full_name='batchtank_messages.BaseMessage.getSensor', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=40,
  serialized_end=247,
)


_REGISTER = descriptor.Descriptor(
  name='Register',
  full_name='batchtank_messages.Register',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='batchtank_messages.Register.type', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='periodTime', full_name='batchtank_messages.Register.periodTime', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=249,
  serialized_end=325,
)


_CONTROLSIGNAL = descriptor.Descriptor(
  name='ControlSignal',
  full_name='batchtank_messages.ControlSignal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='batchtank_messages.ControlSignal.value', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='batchtank_messages.ControlSignal.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=327,
  serialized_end=403,
)


_SAMPLE = descriptor.Descriptor(
  name='Sample',
  full_name='batchtank_messages.Sample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='batchtank_messages.Sample.value', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='batchtank_messages.Sample.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=405,
  serialized_end=474,
)

_BASEMESSAGE.fields_by_name['sample'].message_type = _SAMPLE
_BASEMESSAGE.fields_by_name['signal'].message_type = _CONTROLSIGNAL
_BASEMESSAGE.fields_by_name['register'].message_type = _REGISTER
_BASEMESSAGE.fields_by_name['getSensor'].enum_type = _SENSORTYPE
_REGISTER.fields_by_name['type'].enum_type = _SENSORTYPE
_CONTROLSIGNAL.fields_by_name['type'].enum_type = _OUTPUTTYPE
_SAMPLE.fields_by_name['type'].enum_type = _SENSORTYPE
DESCRIPTOR.message_types_by_name['BaseMessage'] = _BASEMESSAGE
DESCRIPTOR.message_types_by_name['Register'] = _REGISTER
DESCRIPTOR.message_types_by_name['ControlSignal'] = _CONTROLSIGNAL
DESCRIPTOR.message_types_by_name['Sample'] = _SAMPLE

class BaseMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BASEMESSAGE
  
  # @@protoc_insertion_point(class_scope:batchtank_messages.BaseMessage)

class Register(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REGISTER
  
  # @@protoc_insertion_point(class_scope:batchtank_messages.Register)

class ControlSignal(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTROLSIGNAL
  
  # @@protoc_insertion_point(class_scope:batchtank_messages.ControlSignal)

class Sample(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SAMPLE
  
  # @@protoc_insertion_point(class_scope:batchtank_messages.Sample)

# @@protoc_insertion_point(module_scope)
